### ISSUE TITLE
chore: make a pipeline to reduce bugs and errors

### ISSUE THREAD

**Issue by arjunr00** [UCLA-Creative-Labs/sunshine-redesign#13]
Set up basic pipeline for `sunshine-redesign`:
- [x] mergify
- [x] make labels for issues
- [x] issue templates for feat, bugs, chore, design
- [x] generate empty CONTRIBUTING.md
- [x] generate empty DESIGN_GUIDELINE.md

**Comment by BryanPan342** [comment]
issues to add:

- feat
- bug
- chore
- design
- documentation

- effort/small
- effort/medium
- effort/large

- pr/do-not-merge
- pr/work-in-progress

- in-progress
- guidance
- tracking
